import 'package:sample_to_do_app_ui/models/sub_task_model.dart';
import 'package:sample_to_do_app_ui/models/task_status_enum.dart';

class TaskModel {
  int? id; // Make id nullable
  DateTime dateTime;
  TaskStatus taskStatus;
  List<SubTaskModel>? subTasksModel;

  TaskModel({
    this.id, // id is optional since it will be generated by the database
    required this.dateTime,
    required this.taskStatus,
    this.subTasksModel,
  });

  factory TaskModel.fromMap(Map<String, dynamic> map) {
    // Decode subTasksModel from map
    return TaskModel(
      id: map['id'] as int,
      dateTime: DateTime.fromMillisecondsSinceEpoch(map['dateTime'] as int),
      taskStatus: TaskStatusExtension.fromValue(map['taskStatus'] as int),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'dateTime': dateTime.millisecondsSinceEpoch,
      'taskStatus': taskStatus.value,
    };
  }

  TaskModel copyWith({
    DateTime? dateTime,
    TaskStatus? taskStatus,
    List<SubTaskModel>? subTasksModel,
  }) {
    return TaskModel(
      dateTime: dateTime ?? this.dateTime,
      taskStatus: taskStatus ?? this.taskStatus,
      subTasksModel: subTasksModel ?? this.subTasksModel,
    );
  }
}
